### ISSUE TITLE
Whatsapp API

### ISSUE THREAD

**Issue by gagustavo** [DiegoMagg/Snacker#1]
Fica como dica para o futuro, se quiser, tentar usar a API do Whatsapp para pegar os dados, em vez de exportar o TXT.

Como é uma tarefa simples, talvez não compense. Nem sei se isso é viável.

Só uma sugestão mesmo.

**Comment by DiegoMagg** [comment]
A manipulação da API do WhatsApp neste caso é algo custoso, é necessário por exemplo, manter um sim card o que é desnecessário no caso de uso deste script.
